name: rosetta_pydata_integration
dependencies:
  - python=3.7
  - pip

  - pyrosetta=2019.22
  - dask=2.0
  - distributed=2.0
  - conda-forge::dask-jobqueue=0.4

  - pandas
  - scipy
  - biopython
  - matplotlib
  - seaborn
  - conda-forge::py3dmol=0.8

  - psutil
  - requests

  - jupyterlab=0.35
  - nb_conda_kernels>=2.2
  - nb_conda>=2.2

  - ipython
  - ipykernel
