dependencies:
  - python=3.7
  - ipython
  - http://conda.graylab.jhu.edu::pyrosetta=2019.22
  - dask=2.0
  - distributed=2.0
  - matplotlib
  - seaborn
  - conda-forge::py3dmol

  - conda-forge::jupyterlab
  - conda-forge::nb_conda_kernels>=2.2
  - conda-forge::nb_conda
  - ipykernel

  - simplistix::picky-conda
